# https://external-secrets.io/latest/examples/bitwarden/
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-admin-credentials
  namespace: jenkins
spec:
  target:
    name: jenkins-admin-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: '{{ .username }}'
        password: '{{ .password }}'
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 87caf0ab-2c66-43a3-aadf-7d6be572b95f
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 87caf0ab-2c66-43a3-aadf-7d6be572b95f
        property: password
