controller:
  componentName: "jenkins-controller"
  image:
    registry: "docker.io"
    repository: "jenkins/jenkins"
    tag: 2.569-slim-jdk25
  JCasC:
    securityRealm: ""
  admin:
    createSecret: false
    existingSecret: jenkins-admin-credentials
    userKey: username
    passwordKey: password
  ingress:
    enabled: true
    pathType: Prefix
    apiVersion: "networking.k8s.io/v1"
    labels: {}
    annotations:
      spec.ingressClassName: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    ingressClassName: traefik
    path: /
    hostName: ci.mydomain.tld
    resourceRootUrl:
    tls: 
      - secretName: jenkins-tls
        hosts:
          - ci.mydomain.tld
  installPlugins:
    - kubernetes:4423.vb_59f230b_ce53
    - workflow-aggregator:608.v67378e9d3db_1
    - git:5.10.1
    - configuration-as-code:2088.ve3b_42c663c80
    - gitea:273.vb_78d13f6d9a_d
persistence:
  enabled: true
  existingClaim:
  storageClass: longhorn
  accessMode: "ReadWriteOnce"
  size: "8Gi"


  # 'name' is a name of an existing secret in the same namespace as jenkins,
  # 'keyName' is the name of one of the keys inside the current secret.
  # the 'name' and 'keyName' are concatenated with a '-' in between, so for example:
  # an existing secret "secret-credentials" and a key inside it named "github-password" should be used in JCasC as ${secret-credentials-github-password}
  # 'name' and 'keyName' must be lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-',
  # and must start and end with an alphanumeric character (e.g. 'my-name', or '123-abc')
  # existingSecret existing secret "secret-credentials" and a key inside it named "github-username" should be used in JCasC as ${github-username}
  # When using existingSecret no need to specify the keyName under additionalExistingSecrets.
existingSecret:
  name: gitea-credentials
  keyName: password