---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-credentials
  namespace: harbor
spec:
  target:
    name: harbor-admin-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: '{{ .username }}'
        password: '{{ .password }}'
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ba1bde49-2139-4463-929a-1fc34c5387af
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ba1bde49-2139-4463-929a-1fc34c5387af
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core
  namespace: harbor
spec:
  target:
    name: harbor-core
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CSRF_KEY: '{{ .CSRF_KEY }}'
        POSTGRESQL_PASSWORD: '{{ .POSTGRESQL_PASSWORD }}'
        REGISTRY_CREDENTIAL_PASSWORD: '{{ .REGISTRY_CREDENTIAL_PASSWORD }}'
        secret: '{{ .secret }}'
        secretKey: '{{ .secretKey }}'
        tls.crt: '{{ .tlscrt | b64dec }}'
        tls.key: '{{ .tlskey | b64dec }}'
  data:
    - secretKey: CSRF_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 911ac0be-8240-4b25-bb8c-6611c913bff0
        property: CSRF_KEY
    - secretKey: POSTGRESQL_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 911ac0be-8240-4b25-bb8c-6611c913bff0
        property: POSTGRESQL_PASSWORD
    - secretKey: REGISTRY_CREDENTIAL_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 911ac0be-8240-4b25-bb8c-6611c913bff0
        property: REGISTRY_CREDENTIAL_PASSWORD
    - secretKey: secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 911ac0be-8240-4b25-bb8c-6611c913bff0
        property: secret
    - secretKey: secretKey
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 911ac0be-8240-4b25-bb8c-6611c913bff0
        property: secretKey
    - secretKey: tlscrt
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 911ac0be-8240-4b25-bb8c-6611c913bff0
        property: tls.crt
    - secretKey: tlskey
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 911ac0be-8240-4b25-bb8c-6611c913bff0
        property: tls.key
