{{- range .Values.applications }}
{{- $config := $.Values.config -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name | quote }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: {{ .namespace | default .name | quote }}
    server: {{ $config.spec.destination.server | quote }}
  {{- if .sources }}
  sources:
    {{- toYaml .sources | nindent 4 }}
    {{- if not .helm }}
      helm:
        valueFiles:
        - $values/{{ .name }}/values.yaml
    {{- end }}
    - repoURL: 'http://gitea-http.gitea.svc:3000/gitea_admin/homelab-gitops.git'
      targetRevision: HEAD
      ref: values
  {{- else }}
  source:
    path: {{ .path | default .name | quote }}
    repoURL: {{ $config.spec.source.repoURL }}
    targetRevision: {{ $config.spec.source.targetRevision }}
    {{- with .tool }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # automated:
      # prune: true
      # selfHeal: true
---
{{ end -}}