# https://external-secrets.io/latest/examples/bitwarden/
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-admin-credentials
  namespace: nextcloud
spec:
  target:
    name: nextcloud-admin-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: '{{ .username }}'
        password: '{{ .password }}'
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: aaaabbbb-cccc-dddd-eeee-000011112222
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: aaaabbbb-cccc-dddd-eeee-000011112222
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db-credentials
  namespace: nextcloud
spec:
  target:
    name: nextcloud-db-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: '{{ .username }}'
        mariadb-password: '{{ .mariadbPassword }}'
        mariadb-replication-password: '{{ .mariadbReplicationPassword }}'
        mariadb-root-password: '{{ .mariadbRootPassword }}'
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: aaaabbbb-cccc-dddd-eeee-000011112222
        property: username
    - secretKey: mariadbPassword
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: aaaabbbb-cccc-dddd-eeee-000011112222
        property: mariadb-password
    - secretKey: mariadbReplicationPassword
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: aaaabbbb-cccc-dddd-eeee-000011112222
        property: mariadb-replication-password
    - secretKey: mariadbRootPassword
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: aaaabbbb-cccc-dddd-eeee-000011112222
        property: mariadb-root-password