apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  target:
    name: cloudflare-api-token-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        api-token: '{{ .api_token }}'
  data:
    - secretKey: api_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 74b16de7-da78-4513-903b-f9588ebb1699
        property: api-token