apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  target:
    name: cloudflare-api-token-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        api-token: '{{ .api-token }}'
  data:
    - secretKey: api-token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: aaaabbbb-cccc-dddd-eeee-000011112222
        property: api-token